from typing import Protocol
from fast_api_tutorial.schemas import CreateUserRequest, UserDB


class UserRepository(Protocol):

    def add(self, entity: CreateUserRequest) -> None: ...

    def get_from_email(self, email: str) -> UserDB: ...

    def get_all(self) -> list[UserDB]: ...

    def get_paginated(self, page: int, size: int) -> list[UserDB]: ...

    def get(self, id: int) -> UserDB: ...

    def update(self, id: int, entity: CreateUserRequest) -> None: ...

    def delete(self, id: int) -> None: ...
